### ISSUE TITLE
dcm2niix image needs to be updated badly

### ISSUE THREAD

**Issue by dmd** [NrgXnat/docker-images#6]
Could the dcm2niix image please be updated? dcm2niix has had numerous bugfixes and improvements since v1.0.20180622.  For instance, we have a Prisma FIT which uses some dicom features that v1.0.20180622 can't handle, but v1.0.20211006 can.

**Comment by dmd** [comment]
Thanks. Can you add a note here when you've pushed to Hub?

**Comment by dmd** [comment]
Oh, you already did. Thanks!

**Comment by kelseym** [comment]
Update pushed to hub.docker.com 'xnat/dcm2niix:1.6' & 'xnat/dcm2niix:latest'

**Comment by nshreyasvi** [comment]
Hello,
I was trying to run dcm2niix image using XNAT container but it is unable to run and is showing the following error ```Error: Unable to find any DICOM images in /input (or subfolders 5 deep)```. I would like to know if the commands.json and dockerfile for dcm2niix could be updated so that it works with the latest deployed version of XNAT.

**Comment by kelseym** [comment]
Hi there,
I have generally seen that error message when forgetting to setup the Path Translation feature in Container Service.  
Are your XNAT components deployed using the docker-compose project, or something similar, that would cause XNAT/Tomcat to see host file paths differently than your processing containers?  If so, you might checkout instructions for Path Translation [here](https://github.com/NrgXnat/xnat-docker-compose#path-translation).
